#: File I/O.
DEFAULT_BLOCK_SIZE_FOR_FILE_IO = 8192

#: File search - mostly.
FOLLOW_MOUNT_POINTS_BY_DEFAULT = True
FOLLOW_SYMLINKS_BY_DEFAULT = False
INCLUDE_FILE_HASHES_BY_DEFAULT = True

#: String comparison.
STRING_COMPARISON_IS_CASE_SENSITIVE_BY_DEFAULT = False
